config/routes.rb
Rails.application.routes.draw do
  root "pfs#top"
  resources :pfs, only: [:index] do
    collection do
      get :top
      get :about
      get :roadbiker
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :basic_auth

  # private

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == 'admin' && password == '2222'
  #   end
  # end
end

app/controllers/pfs_controller.rb
class PfsController < ApplicationController
  def top

    
  end

  def about
    
  end

  def index
    
  end

  def roadbiker
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pfs_helper.rb
module PfsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    -# #stalker<i class="fas fa-star"></i>
    %i.fas.fa-star#stalker
    = yield

app/views/pfs/_load.html.haml
.load#page-loading
  .loading#loading
    = "l o a d i n g"

app/views/pfs/about.html.haml
.pfs
  .about
    .box#about
      -# .box__home
      -#   = link_to "H O M E",root_path
      -# .box__title
      -#   = "A b o u t"
      .box__contents
        .box__contents__header
          = "伊東 祐一郎"
        .box__contents__main
          .box__contents__main__first
            .box__contents__main__first__text
              = "1998年11月15日生まれ"
            .box__contents__main__first__text
              = "2019年11月ごろにプログラミングを知る"
            .box__contents__main__first__text
              = "書店でJavaの参考書を購入"
            .box__contents__main__first__text
              = "独学で学び以下のような数当てゲームを作成"
            .box__contents__main__first__image
              = image_tag "firstapp-java.png",width:"90%"
            .box__contents__main__first__text
              = "自らの手でコードを書きプログラムが動くという面白さを知る"
            .box__contents__main__first__text
              = "同時に自分の実力と実務レベルに大きな差があることを知り独学での限界を感じる。"
            .box__contents__main__first__text
              = "自分に合いそうなプログラミングスクールを探す"
          .box__contents__main__second
            .box__contents__main__second__title
              = "2019年12月9日 TECH::EXPERTに入学"
              .box__contents__main__second__text
                = "スクールではメッセージの送信、チャットグループの作成、などができるchat-spaceという名前のアプリを開発"
              .box__contents__main__second__text
                = "chat-spaceを開発する過程で、Html,Css,Ruby,JavaScriptを習得"
              .box__contents__main__second__text
                = "スクールに通ってから2ヶ月ほどで自らの力でWebアプリケーションを作る力が身についた"
          .box__contents__main__third
            .box__contents__main__third__title
              = "興味があること"
            .box__contents__main__third__text
              = "pythonを使用した機械学習"
            .box__contents__main__third__text
          .box__contents__main__bottom
            = "Thank You for Watching!!"
            

app/views/pfs/index.html.haml
.pfs
  .index
    .contents#portfolio-contents
      -# .contents__home
      -#   = link_to "H O M E",root_path
      -# .contents__title
      -#   = "P o r t f o l i o"
      .contents__info
        = "作品紹介"
      .contents__main
        .contents__main__road
          .contents__main__road__header
            = link_to roadbiker_pfs_path do
              = "RoadBiker"
          .contents__main__road__image
            = link_to roadbiker_pfs_path do
              = image_tag "roadbiker.png",width:"400px"
          .contents__main__road__text
            = "趣味のRoadBikeについてのWebアプリケーション"
        

    

app/views/pfs/roadbiker.html.haml
.pf#application
  -# #click
  .roadbiker
    .road-page#roadbiker
      .road-page__home
        = link_to "H O M E",root_path
      .road-page__portfolio
        = link_to "portfolio",pfs_path
      .road-page__title
        = "RoadBiker"
      .road-page__image
        = image_tag "roadbiker.png",width:"500px"
      .road-page__contents
        .road-page__contents__box
          .road-page__contents__box__left
            .road-page__contents__box__left__first
              .road-page__contents__box__left__first__title
                = "ロードバイクの総合的なアプリケーション"
              .road-page__contents__box__left__first__text
                = "ロードバイクの専門的なサイトが欲しかったので自ら作成"
              .road-page__contents__box__left__first__text
                = "主な機能として検索機能、投稿機能、通報機能がある"
            .road-page__contents__box__left__second
              .road-page__contents__box__left__second__title
                = "制作期間"
              .road-page__contents__box__left__second__text
                = "2020年1月中ごろから2020年2月末"
              .road-page__contents__box__left__second__text
                = "ただし、1月29日から2月21日の間はチーム開発が多忙だったため開発を中断"
          .road-page__contents__box__right
            .road-page__contents__box__right__first
              .road-page__contents__box__right__first__title
                = "使用技術"
              .road-page__contents__box__right__first__text
                = "html,css,jquery,ruby,rails"
            .road-page__contents__box__right__second
              .road-page__contents__box__right__second__title
                = "アプリのリンク"
              .road-page__contents__box__right__second__text
                = link_to "RoadBiker","https://roadbiker.herokuapp.com/",class:"roadbiker-link"
              .road-page__contents__box__right__second__text
                = link_to "Git Hub ReadMe","https://github.com/yuichiro-cloud/roadbike-portal",class:"roadbiker-readme"

app/views/pfs/top.html.haml
.pfs
  .top
    .contents
      -# .load#page-loading
      -#   .loading#loading
      -#     = "l o a d i n g"
      .loaded#page-loaded
        .box#menu-box
          -# .box__left
          -#   .box__left__about
          -#     = link_to "a b o u t",about_pfs_path
          -#   .box__left__pf
          -#     = link_to "p o r t f o l i o",pfs_path
          -# .box__btn
          -#   = "menu"
        .main
        -#   .main__welcome
            -# = "Welcome"
          -# .main__pf
            -# = "portfolio"
          -# .main__creator
          -#   = "creator"
          -# .main__name
          -#   = "Yuichiro Ito"
        -# .left
        -#   = link_to "H O M E",root_path
          -# = "Home"
        -# .right#menu-btn
        -#   = "menu"